### ISSUE TITLE
Implement more annotation types

### ISSUE THREAD

**Issue by WilliamHYZhang** [KarthikRIyer/swiftplot#70]
Hi,

I was interesting in possibly making more annotation types conforming to the new protocol. Currently, I plan on adding support for arrows as well as boxes.

For arrows, I was thinking of perhaps specifying types of arrows from their symbols (e.g. ➔, ➙, ➛, ➜, ➝, ➡, etc) could all be options, other arguments would be location (where tip of arrow is pointing), color, size, etc. and we would use the underlying drawText feature and do a little math to find out the location to pass.

For boxes, I was thinking about using the underlying drawRect feature, aguments would be size, location (would you all prefer it as the center of the box?), size, etc. Please tell me what you all think!

Thank you and looking forward for more contributions,
William

**Comment by KarthikRIyer** [comment]
We can take a look at the kind of annotations matplotlib provides here: https://matplotlib.org/3.1.1/tutorials/text/annotations.html

For arrows, we can take in its start point and end point (instead of size), color, thickness/stroke width maybe? Instead of using symbols, we should think of names/symbol notations for each kind of arrow. 
This will be more convenient. You will also have to write some functions for each renderer to support drawing arrows.
I'm not sure what you mean by 

> do a little math to find out the location to pass

For boxes, I think drawing a simple rectangle would be of no use in general. We should support drawing a bounding rectangle for a text label. You should be able to get the `Size` of any text, and you could add some offset to that Size to get the bounding box for that text. For location we can consider the bottom left corner. In the beginning we can just implement a simple version of this but later on we can extend it to support boxes with a different border color, rounded corners, etc.

**Comment by WilliamHYZhang** [comment]
Thanks for the suggestions! I'll work on the arrow implementation first and submit a PR when I'm done.

**Comment by KarthikRIyer** [comment]
Will you be doing this as part of GCI? If so I just wanted to know if you're able to claim another instance of that task.

**Comment by WilliamHYZhang** [comment]
I would love to! However, I can't find that task anymore since I already completed it. May you please create another task for SwiftPlot contributions so I can claim it? Thank you!
